bytedance/g3

Cargo.lock, Cargo.toml, g3proxy/doc/configuration/values/network.rst, g3proxy/doc/configuration/values/tls.rst, g3tiles/src/config/server/rustls_proxy/host.rs, lib/g3-resolver/Cargo.toml, lib/g3-resolver/src/driver/trust_dns/config.rs, lib/g3-resolver/src/driver/trust_dns/driver.rs, lib/g3-types/Cargo.toml, lib/g3-types/src/net/dns/encryption.rs, lib/g3-types/src/net/host.rs, lib/g3-types/src/net/rustls/client.rs, lib/g3-types/src/net/rustls/server.rs
=> update to rustls 0.21

doc/dev-setup.md
=> fix:readme g3proxy dev setup

g3proxy/doc/configuration/servers/plain_tcp_port.rst, g3proxy/doc/configuration/servers/plain_tls_port.rst, g3proxy/examples/chain_proxy_protocol/g3proxy.yaml, g3proxy/src/serve/plain_tcp_port/mod.rs, g3proxy/src/serve/plain_tls_port/mod.rs, lib/g3-daemon/src/listen/stats.rs, lib/g3-io-ext/src/haproxy/mod.rs, lib/g3-io-ext/src/haproxy/v1.rs, lib/g3-io-ext/src/haproxy/v2.rs
should fix https://github.com/bytedance/g3/issues/127
=> g3proxy: support proxy protocol v1 for incoming connections

Cargo.lock, lib/g3-resolver/Cargo.toml
=> switch back to use c-ares

g3proxy/UserGuide.zh_CN.md
Fixed issue https://github.com/bytedance/g3/issues/153
=> fix wrong cfg path in g3proxy/UserGuide.zh_CN.md

g3proxy/UserGuide.en_US.md
This is a first pass at an english user guide. I used ChatGPT to do most of the work so it may not be fully correct but I found it helpful.
=> English User Guide

.github/workflows/linux-musl.yml, lib/g3-io-ext/src/udp/ext.rs
Close https://github.com/bytedance/g3/issues/189.
=> fix linux musl build

g3proxy/doc/configuration/auditors/index.rst, g3proxy/doc/configuration/values/dpi.rst, g3proxy/src/audit/handle.rs, g3proxy/src/config/audit/auditor.rs, g3proxy/src/inspect/http/v2/error.rs, g3proxy/src/inspect/http/v2/mod.rs, g3proxy/src/inspect/mod.rs, g3proxy/src/inspect/smtp/mod.rs, g3proxy/src/inspect/tls/mod.rs, g3proxy/src/inspect/tls/modern.rs, lib/g3-dpi/src/config/mod.rs, lib/g3-dpi/src/lib.rs, lib/g3-smtp-proto/src/response/encoder.rs, lib/g3-types/src/net/tls/alpn.rs, lib/g3-yaml/src/value/dpi/inspect.rs, lib/g3-yaml/src/value/dpi/mod.rs
close https://github.com/bytedance/g3/issues/203
=> g3proxy: add protocol inspect policy to h2 and smtp

g3proxy/doc/configuration/auditors/index.rst, g3proxy/doc/configuration/user_group/audit.rst, g3proxy/doc/configuration/values/dpi.rst, g3proxy/src/config/auth/audit/json.rs, g3proxy/src/config/auth/audit/mod.rs, g3proxy/src/config/auth/audit/yaml.rs, g3proxy/src/inspect/stream/mod.rs, g3proxy/src/inspect/stream/object.rs, lib/g3-dpi/src/protocol/mod.rs
close https://github.com/bytedance/g3/issues/231
=> fix panic when data0 inspection timeout

lib/g3-h2/src/body/from_chunked_transfer.rs, lib/g3-h2/src/body/to_chunked_transfer.rs, lib/g3-http/src/body/chunked_decoder.rs, lib/g3-http/src/body/chunked_encoder.rs, lib/g3-http/src/body/chunked_transfer.rs, lib/g3-http/src/body/mod.rs, lib/g3-http/src/body/reader.rs, lib/g3-http/src/lib.rs, lib/g3-icap-client/src/reqmod/h2/bidirectional.rs, lib/g3-icap-client/src/reqmod/h2/forward_body.rs, lib/g3-icap-client/src/reqmod/h2/mod.rs, lib/g3-icap-client/src/reqmod/h2/preview.rs, lib/g3-icap-client/src/reqmod/h2/recv_request.rs, lib/g3-icap-client/src/reqmod/h2/recv_response.rs, lib/g3-icap-client/src/respmod/h2/bidirectional.rs, lib/g3-icap-client/src/respmod/h2/forward_body.rs, lib/g3-icap-client/src/respmod/h2/preview.rs, lib/g3-icap-client/src/respmod/h2/recv_response.rs
close https://github.com/bytedance/g3/issues/235
=> fix http body trailer encoding

g3proxy/src/escape/route_query/cache.rs, g3proxy/src/serve/socks_proxy/task/common.rs, lib/g3-ip-locate/src/config.rs, lib/g3-socket/src/udp.rs, lib/g3-tls-cert/src/agent/config.rs
should close https://github.com/bytedance/g3/issues/237
=> g3proxy: fix bind addr for agent udp connect

.dockerignore, README.md, README.zh_CN.md, g3fcgen/docker/alpine.Dockerfile, g3fcgen/docker/debian.Dockerfile, g3iploc/docker/alpine.Dockerfile, g3iploc/docker/debian.Dockerfile, g3proxy/docker/alpine.Dockerfile, g3proxy/docker/debian.Dockerfile
=> add example Dockerfile

README.ja_JP.md, README.md, README.zh_CN.md
I created Japanese translated README.
=> docs: add Japanese README file

g3proxy/src/auth/source/mod.rs
=> g3proxy: fix dead loop in user fetch job

g3keymess/src/config/log.rs, g3proxy/doc/conf.py, g3proxy/doc/configuration/log/index.rst, g3proxy/examples/inspect_http_proxy/g3proxy.yaml, g3proxy/src/config/log.rs, g3tiles/doc/conf.py, g3tiles/doc/configuration/log/index.rst, g3tiles/src/config/log.rs, lib/g3-daemon/src/log/config.rs, lib/g3-daemon/src/log/process.rs, lib/g3-daemon/src/log/runtime.rs, lib/g3-stdlog/src/format.rs, lib/g3-stdlog/src/lib.rs
close #279.
The structured logs generated for user view can be written to stdout now.
The process logs for debug purpose will still be written to stderr.
=> allow to write structured logs to stdout

g3proxy/docker/lua.alpine.Dockerfile
tested and works
also, switched to cjson cause that's a c module, directly testing if the whole static/dynamic thing works.
it works.
=> Fixed the now-invalid comment about luarocks

g3proxy/README.md, g3proxy/doc/configuration/escapers/comply_audit.rst, g3proxy/doc/configuration/escapers/index.rst, g3proxy/src/audit/mod.rs, g3proxy/src/audit/ops.rs, g3proxy/src/config/escaper/comply_audit.rs, g3proxy/src/config/escaper/mod.rs, g3proxy/src/escape/comply_audit/mod.rs, g3proxy/src/escape/mod.rs, g3proxy/src/escape/ops.rs
=> g3proxy: add comply_audit escaper to overwrite auditor settings

justfile
part of #156
Developer could then run
```
just qa
```
It's not perfect, but it's a possible beginning that is at least better than nothing.
The steps ran are based on the CI cmds I found in your workflows.
Integration tests,
different feature commands,
more complete integrations (e.g. using cargo-hack),
etc...
can all be added there. But can be done step by step, this might already be good enough to start. You tell me.
Or perhaps you do not like it at all and I can close it, also ok.
=> add basic example of justfile

Cargo.lock, g3proxy/src/escape/direct_fixed/stats.rs, g3proxy/src/escape/direct_fixed/tcp_connect/mod.rs, g3proxy/src/escape/direct_float/tcp_connect/mod.rs, g3proxy/src/escape/divert_tcp/stats.rs, g3proxy/src/escape/divert_tcp/tcp_connect/mod.rs, g3proxy/src/escape/dummy_deny/stats.rs, g3proxy/src/escape/mod.rs, g3proxy/src/escape/proxy_float/stats.rs, g3proxy/src/escape/proxy_float/tcp_connect.rs, g3proxy/src/escape/proxy_float/tls_handshake.rs, g3proxy/src/escape/proxy_http/stats.rs, g3proxy/src/escape/proxy_http/tcp_connect/mod.rs, g3proxy/src/escape/proxy_https/mod.rs, g3proxy/src/escape/proxy_https/stats.rs, g3proxy/src/escape/proxy_https/tcp_connect/mod.rs, g3proxy/src/escape/proxy_https/tls_handshake/mod.rs, g3proxy/src/escape/proxy_socks5/stats.rs, g3proxy/src/escape/proxy_socks5/tcp_connect/mod.rs, g3proxy/src/escape/proxy_socks5s/http_forward/mod.rs, g3proxy/src/escape/proxy_socks5s/mod.rs, g3proxy/src/escape/proxy_socks5s/stats.rs, g3proxy/src/escape/proxy_socks5s/tcp_connect/mod.rs, g3proxy/src/escape/proxy_socks5s/tls_handshake/mod.rs, g3proxy/src/escape/stats.rs, g3proxy/src/stat/metrics/escaper.rs, sphinx/g3proxy/metrics/escaper.rst
=> add more metrics to escaper

lib/g3-http/src/uri/well_known/easy_proxy.rs
Use `Scheme` enum directly for HTTP/S protocols rather than resolving all of them every time.
=> refactor: do not compute well known schemes

lib/g3-icap-client/src/service/pool.rs
1. Replaced `try_send` with `send` in order to await for completion and avoid closing new TCP connections immediately due to a full pool_sender cmd buffer channel. 
2. Avoid race condition caused by calling `CheckConnection` for each connection timeout -- connections created within the same `idle_timeout` epoch can create up-to `current_idle..min_idle` connections each
3. Changed `max_idle_count` and `min_idle_count` condition check to avoid immediately closing new connections caused by (1) and (2) -- create connections up-to min_idle only on `check_interval tick` and skip adding existing connections to the re-use pool at max_idle.
=> g3-icap-client: connection pool reuse and idle checks

lib/g3-yaml/src/value/net/buf.rs, lib/g3-yaml/src/value/net/dns.rs, lib/g3-yaml/src/value/net/haproxy.rs, lib/g3-yaml/src/value/net/http.rs, lib/g3-yaml/src/value/net/interface.rs
add unit tests for value/net/buf.rs,dns.rs,haproxy.rs,http.rs,interface.rs
=> test(g3-yaml): add unit tests

lib/g3-yaml/src/value/dpi/http.rs, lib/g3-yaml/src/value/dpi/imap.rs, lib/g3-yaml/src/value/dpi/inspect.rs, lib/g3-yaml/src/value/dpi/portmap.rs, lib/g3-yaml/src/value/dpi/smtp.rs
Add unit tests for value/dpi/http.rs,imap.rs,inspect.rs,portmap.rs,smtp.rs
=> test(g3-yaml): Add unit tests for DPI configuration parsing

lib/g3-yaml/src/value/geoip.rs, lib/g3-yaml/src/value/route/alpn.rs, lib/g3-yaml/src/value/route/host.rs, lib/g3-yaml/src/value/route/uri_path.rs
- Implement tests for geoip value parsing
- Add tests for route value parsing
=> test(g3-yaml): Add unit tests for YAML parsing functions

doc/dev-setup.md, g3mkcert/README.md, lib/g3-io-ext/src/haproxy/v1.rs
=> g3-io-ext: check for valid haproxy-proto v1 preamble

lib/g3-clap/src/http/header.rs, lib/g3-clap/src/humanize/size.rs, lib/g3-clap/src/humanize/time.rs, lib/g3-dpi/tests/dns.rs, lib/g3-dpi/tests/mqtt.rs, lib/g3-dpi/tests/rtmp.rs, lib/g3-dpi/tests/rtsp.rs, lib/g3-dpi/tests/smpp.rs, lib/g3-dpi/tests/stomp.rs
=> add tests for g3-clap and multiple g3-dpi protocols

lib/g3-dpi/tests/ssh.rs, lib/g3-types/src/auth/crypt.rs, lib/g3-types/src/auth/error.rs, lib/g3-types/src/auth/user.rs, lib/g3-types/src/route/alpn.rs, lib/g3-types/src/route/host.rs, lib/g3-types/src/route/uri_path.rs
=> add tests for g3-dpi and g3-types

lib/g3-types/src/net/error.rs, lib/g3-types/src/net/http/keepalive.rs, lib/g3-types/src/net/websocket.rs, lib/g3-types/src/stats/mod.rs, lib/g3-types/src/stats/pool.rs, lib/g3-types/src/stats/tcp.rs, lib/g3-types/src/stats/udp.rs
=> add unit tests for network and stats modules in g3-types

lib/g3-http/src/connect/client.rs, lib/g3-http/src/connect/request.rs, lib/g3-http/src/connect/response.rs
=> add unit tests for HTTP CONNECT client, request and response

lib/g3-fluentd/src/handshake.rs, lib/g3-ftp-client/src/config/yaml.rs, lib/g3-geoip-db/src/record.rs, lib/g3-geoip-types/src/continent.rs, lib/g3-geoip-types/src/country/iso_generated.rs, scripts/generate/country/iso3166_continent.awk, scripts/generate/country/iso3166_test_continent.awk, scripts/generate/country/iso3166_test_variant_count.awk, scripts/generate/country/iso3166_variant_count.awk, scripts/generate/country/update.sh
=> add unit tests for g3-fluentd, g3-ftp-client and g3-geoip-types
